trigger:
- master

name: $(SourceBranchName)_$(Date:yyyy-MM-dd)_$(Rev:.r)

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildDir: 'src'

steps:
- task: DotNetCoreInstaller@1
  displayName: Install .NET Core 3.0
  inputs:
    packageType: 'sdk'
    includePreviewVersions: true
    version: '3.0.x'
    
- task: DotNetCoreInstaller@1
  displayName: Install .NET Core 2.1
  inputs:
    packageType: 'sdk'
    version: '2.1.x'

- task: Bash@3
  displayName: Build
  inputs:
    filePath: 'build.sh'
    failOnStderr: true

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '.artifacts/tests/*.trx'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  displayName: Publish NuGet Package Artifacts
  inputs:
    pathToPublish: .artifacts/packages/*.nupkg
    artifactName: 'NuGet Packages'
  condition: |
    and
    (
      succeeded(),
      eq(variables['system.pullrequest.isfork'], false)
    )
